name: OntaDev_Shulkers
version: '${project.version}'
main: com.ontadev.shulkers.OntaDevShulkersPlugin
api-version: '1.16'
load: POSTWORLD
authors: [ OntaDev ]

depend:
  - OntaDev_Libs
  - LuckPerms
  - WorldEdit
  - WorldGuard
